/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tiendadeciclismo.productos;

import com.mycompany.tiendadeciclismo.MenuPrincipal;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author david
 */
public class CRUDArticulos extends javax.swing.JFrame {

    private gestorTProductosArticulos gestionProducto;
   
    public CRUDArticulos() {
        initComponents();
        gestionProducto = new gestorTProductosArticulos();
        CargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnGestionarProductos = new javax.swing.JButton();
        btnAgregarArticulos = new javax.swing.JButton();
        btnBuscarArticulos = new javax.swing.JButton();
        btnModificarArticulos = new javax.swing.JButton();
        btnEliminarArticulos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        textoNombre = new javax.swing.JTextField();
        textoCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArticulos = new javax.swing.JTable();
        labelMensaje = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Gestionar Productos");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGestionarProductos.setText("Gestionar Tipos de Productos");
        btnGestionarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarProductosActionPerformed(evt);
            }
        });

        btnAgregarArticulos.setBackground(new java.awt.Color(0, 204, 0));
        btnAgregarArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarArticulos.setText("Agregar Articulos");
        btnAgregarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarArticulosActionPerformed(evt);
            }
        });

        btnBuscarArticulos.setText("Buscar Articulos");
        btnBuscarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArticulosActionPerformed(evt);
            }
        });

        btnModificarArticulos.setText("Modificar Articulos");
        btnModificarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarArticulosActionPerformed(evt);
            }
        });

        btnEliminarArticulos.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminarArticulos.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarArticulos.setText("Eliminar Articulos");
        btnEliminarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarArticulosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Gestionar Articulos");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        textoNombre.setText(" ");

        jLabel1.setText("Nombre: ");

        jLabel4.setText("Codigo: ");

        tablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Codigo Tipo", "Nombre", "Tipo", "Tamaño", "Marca", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaArticulos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnGestionarProductos)
                                        .addComponent(btnVolver)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 52, Short.MAX_VALUE)
                                        .addComponent(btnAgregarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnModificarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnEliminarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarArticulos)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarArticulos)
                    .addComponent(btnEliminarArticulos)
                    .addComponent(btnModificarArticulos)
                    .addComponent(btnGestionarProductos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       MenuPrincipal menuPrincipal = new MenuPrincipal();
       menuPrincipal.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGestionarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarProductosActionPerformed
        CRUDTproducto gestionProductos = new CRUDTproducto();
        gestionProductos.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnGestionarProductosActionPerformed

    private void btnAgregarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarArticulosActionPerformed
        if (gestionProducto.getListaTProducto().isEmpty()){
            labelMensaje.setText("Primero se debe crear al menos 1 tipo de producto");
        }
        else {
            AgregarArticulo agregar = new AgregarArticulo(null);
            agregar.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnAgregarArticulosActionPerformed

    private void btnBuscarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArticulosActionPerformed
       ArrayList<Articulo> listaArticulos = gestionProducto.getListaArticulos();
    DefaultTableModel model = (DefaultTableModel) tablaArticulos.getModel();
    model.setRowCount(0); // Limpiar tabla

    int codigo = -1;
    String nombre = textoNombre.getText().trim();

    // Validar entrada de código
    if (!textoCodigo.getText().isEmpty()) {
        try {
            codigo = Integer.parseInt(textoCodigo.getText().trim());
            labelMensaje.setText(" ");
        } catch (NumberFormatException e) {
            labelMensaje.setText("El código debe ser un número");
            return; // Salir si el código no es válido
        }
    }

    // Si ambos campos están vacíos, cargar todos los productos
    if (nombre.isEmpty() && codigo == -1) {
        CargarTabla();
        return;
    }

    // Buscar en la lista de productos
    boolean encontrado = false;
    for (Articulo articulo : listaArticulos) {
        // Comparar por nombre o código
        if ((!nombre.isEmpty() && articulo.getNombre().equalsIgnoreCase(nombre)) ||
            (codigo != -1 && articulo.getCodigo() == codigo)) {
            model.addRow(new Object[]{
                articulo.getCodigo(),
                articulo.getCodigoTipoProducto(),
                articulo.getNombre(),
                articulo.getTipo(),
                articulo.getTamano(),
                articulo.getMarca(),
                articulo.getPrecio(),
                articulo.getCantidad()
            });
            encontrado = true;
        }
    }

    // Mostrar mensaje si no hay resultados
    if (!encontrado) {
        labelMensaje.setText("No se encontraron articulos con los criterios ingresados.");
    }
    }//GEN-LAST:event_btnBuscarArticulosActionPerformed

    private void btnModificarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarArticulosActionPerformed
        int seleccion = tablaArticulos.getSelectedRow();
        if (seleccion == -1){
            labelMensaje.setText("Primero Seleccione un tipo de producto");
            
        }
        else {
            int codigo = Integer.parseInt(tablaArticulos.getValueAt(seleccion, 0).toString());
            Articulo modificar = gestionProducto.buscarArticulo(codigo);
            ModificarArticulo panelModificar = new ModificarArticulo(modificar);
            panelModificar.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_btnModificarArticulosActionPerformed

    private void btnEliminarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarArticulosActionPerformed
        int seleccion = tablaArticulos.getSelectedRow();
        if (seleccion == -1){
            labelMensaje.setText("Primero Seleccione un tipo de producto");
            
        }
        else {
            int codigo = Integer.parseInt(tablaArticulos.getValueAt(seleccion, 0).toString());
            Articulo eliminar = gestionProducto.buscarArticulo(codigo);
            EliminarArticulo panelModificar = new EliminarArticulo(eliminar);
            panelModificar.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnEliminarArticulosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDArticulos().setVisible(true);
            }
        });
    }
    
    public gestorTProductosArticulos getGestor(){
        return gestionProducto;
    }
    private void CargarTabla(){
        ArrayList<Articulo> listaArticulos = gestionProducto.getListaArticulos();
        DefaultTableModel model = (DefaultTableModel) tablaArticulos.getModel();
        model.setRowCount(0); // Limpiar tabla
        
        for (Articulo articulo : listaArticulos){
            
            
            model.addRow(new Object[]{
                articulo.getCodigo(),
                articulo.getCodigoTipoProducto(),
                articulo.getNombre(),
                articulo.getTipo(),
                articulo.getTamano(),
                articulo.getMarca(),
                articulo.getPrecio(),
                articulo.getCantidad()
            
            });
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarArticulos;
    private javax.swing.JButton btnBuscarArticulos;
    private javax.swing.JButton btnEliminarArticulos;
    private javax.swing.JButton btnGestionarProductos;
    private javax.swing.JButton btnModificarArticulos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JTable tablaArticulos;
    private javax.swing.JTextField textoCodigo;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables
}
