/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tiendadeciclismo.productos;

/**
 *
 * @author david
 */
public class ModificarArticulo extends javax.swing.JFrame {

    /**
     * Creates new form ModificarArticulo
     */
    private gestorTProductosArticulos gestor;
    private Articulo articulo;
    public ModificarArticulo(Articulo articulo) {
        initComponents();
        this.articulo = articulo;
        gestor = new gestorTProductosArticulos();
        labelNombre.setText("Nombre: " + articulo.getNombre());
        labelCodigo.setText("Codigo tipo de producto: " + articulo.getCodigoTipoProducto());
        labelTipo.setText("Tipo:  "+ articulo.getTipo());
        labelTamano.setText("Tamaño: " + articulo.getTamano());
        labelMarca.setText("Marca: "+ articulo.getMarca());
        labelPrecio.setText("Precio: "+ articulo.getPrecio());
        labelCantidad.setText("Cantidad: " + articulo.getCantidad());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelNombre1 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelCodigo = new javax.swing.JLabel();
        labelNombre2 = new javax.swing.JLabel();
        textCodigoTProducto = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();
        labelNombre3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        labelTamano = new javax.swing.JLabel();
        labelNombre4 = new javax.swing.JLabel();
        comboTamano = new javax.swing.JComboBox<>();
        labelMarca = new javax.swing.JLabel();
        labelNombre5 = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        labelNombre6 = new javax.swing.JLabel();
        textMarca = new javax.swing.JTextField();
        labelCantidad = new javax.swing.JLabel();
        labelNombre7 = new javax.swing.JLabel();
        textCantidad = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        labelMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TITULO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TITULO.setText("Artículo");

        labelNombre.setText("Nombre:");

        labelNombre1.setText("Nuevo Nombre:");

        labelCodigo.setText("Codigo del tipo:");

        labelNombre2.setText("Nuevo Codigo: ");

        labelTipo.setText("Tipo:");

        labelNombre3.setText("Nuevo Tipo: ");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bicicleta", "Accesiorios", "Suplementos Alimenticios" }));
        comboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoActionPerformed(evt);
            }
        });

        labelTamano.setText("Tamaño:");

        labelNombre4.setText("Nuevo Precio:");

        comboTamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "16", "22", "27", "27.5", "29" }));

        labelMarca.setText("Marca: ");

        labelNombre5.setText("Nuevo Tamaño: ");

        labelPrecio.setText("Precio: ");

        labelNombre6.setText("Nueva Marca:");

        labelCantidad.setText("Cantidad:");

        labelNombre7.setText("Nueva Cantidad:");

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(153, 255, 153));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboTamano, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGuardar))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textCodigoTProducto))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(labelTamano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textMarca))
                                            .addComponent(labelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(labelCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TITULO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre1)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre2)
                    .addComponent(textCodigoTProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre3)
                    .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTamano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre6)
                    .addComponent(textMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre4)
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCantidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre7)
                    .addComponent(textCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVolver)
                            .addComponent(btnGuardar))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(labelMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        String tipo = (String) comboTipo.getSelectedItem();
        if (!tipo.equals("Bicicleta")){
            comboTamano.setEnabled(false);
            
            
        }
        else {
            comboTamano.setEnabled(true);
        }
    }//GEN-LAST:event_comboTipoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    labelMensaje.setText("");

    int codigo = 0;
    int intprecio = 0;
    int intcantidad = 0;
    float inttamano = 0;

    String nombre = textNombre.getText().trim();
    String codigoTP = textCodigoTProducto.getText().trim();
    String tipo = (String) comboTipo.getSelectedItem();
    String tamano = (String) comboTamano.getSelectedItem();
    String marca = textMarca.getText().trim();
    String precio = textPrecio.getText().trim();
    String cantidad = textCantidad.getText().trim();

    // Buscar el artículo por código
    Articulo articuloLista = null;
    for (Articulo articuloEnLista : gestor.getListaArticulos()) {
        if (articuloEnLista.getCodigo() == articulo.getCodigo()) {
            articuloLista = articuloEnLista;
            break;
        }
    }

    if (articuloLista == null) {
        labelMensaje.setText("Artículo no encontrado");
        return;
    }

    // Verificar y modificar campos que no están vacíos
    if (!nombre.isEmpty()) {
        articuloLista.setNombre(nombre);
    }

    if (!codigoTP.isEmpty()) {
        try {
            codigo = Integer.parseInt(codigoTP);
            if (!gestor.verificarTProducto(codigo)) {
                labelMensaje.setText("El código no se encuentra en los tipos de productos");
                return;
            }
            articuloLista.setCodigoTipoProducto(codigo);
        } catch (NumberFormatException e) {
            labelMensaje.setText("El código del tipo de producto debe ser un número");
            return;
        }
    }

    if (!marca.isEmpty()) {
        articuloLista.setMarca(marca);
    }

    if (!precio.isEmpty()) {
        try {
            intprecio = Integer.parseInt(precio);
            articuloLista.setPrecio(intprecio);
        } catch (NumberFormatException e) {
            labelMensaje.setText("El precio debe ser un número");
            return;
        }
    }

    if (!cantidad.isEmpty()) {
        try {
            intcantidad = Integer.parseInt(cantidad);
            articuloLista.setCantidad(intcantidad);
        } catch (NumberFormatException e) {
            labelMensaje.setText("La cantidad debe ser un número");
            return;
        }
    }
    articuloLista.setTipo(tipo);
    if (tipo.equals("Bicicleta")) {
        try {
            inttamano = Float.parseFloat(tamano);
            articuloLista.setTamano(inttamano);
        } catch (NumberFormatException e) {
            labelMensaje.setText("El tamaño debe ser un número válido");
            return;
        }
    } else {
        articuloLista.setTamano(0); // Si no es bicicleta, el tamaño es 0
    }
    
    // Mensaje de éxito y limpiar campos
    labelMensaje.setText("Artículo actualizado correctamente");
    textNombre.setText("");
    textCodigoTProducto.setText("");
    textMarca.setText("");
    textPrecio.setText("");
    textCantidad.setText("");
    articulo = articuloLista;
    labelNombre.setText("Nombre: " + articulo.getNombre());
        labelCodigo.setText("Codigo tipo de producto: " + articulo.getCodigoTipoProducto());
        labelTipo.setText("Tipo:  "+ articulo.getTipo());
        labelTamano.setText("Tamaño: " + articulo.getTamano());
        labelMarca.setText("Marca: "+ articulo.getMarca());
        labelPrecio.setText("Precio: "+ articulo.getPrecio());
        labelCantidad.setText("Cantidad: " + articulo.getCantidad());
    gestor.guardarArticulos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        CRUDArticulos menu = new CRUDArticulos();
        menu.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarArticulo(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> comboTamano;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelMarca;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombre1;
    private javax.swing.JLabel labelNombre2;
    private javax.swing.JLabel labelNombre3;
    private javax.swing.JLabel labelNombre4;
    private javax.swing.JLabel labelNombre5;
    private javax.swing.JLabel labelNombre6;
    private javax.swing.JLabel labelNombre7;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelTamano;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JTextField textCantidad;
    private javax.swing.JTextField textCodigoTProducto;
    private javax.swing.JTextField textMarca;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables
}
